# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CityOSAir' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CityOSAir
  	pod 'Charts'
    pod 'RealmSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Alamofire'
    pod 'ReachabilitySwift'
    pod 'UrbanAirship-iOS-SDK'
    pod 'SnapKit'
    pod 'GoogleSignIn'
    pod 'FacebookSDK'
    pod 'FacebookSDK/LoginKit'
    pod 'SwiftyBeaver'
    pod 'KeychainAccess'
    pod 'SVProgressHUD'
    pod 'Cluster'
    
  target 'CityOSAirTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
